version: "3.0"
services:
    torserv:
        build:
            context: .
            dockerfile: TorDockerfile
        env_file:
          - ".env"
        environment:
            - C_FORCE_ROOT=1
    torosya:
        build:
          context: .
          dockerfile: Dockerfile
        env_file:
          - ".env"
        environment:
          - TOR_SERVER_HOST=torserv
        volumes:
          - "./data:/app/data"
        depends_on:
          - torserv